#!/bin/bash -e

url=$(git config --get remote.origin.url)

git clone $url pub
cd pub
git checkout --orphan gh-pages
git rm -rf .

touch README.mkd
git add README.mkd
git commit -m 'initial GitHub Pages' || true

git push -u -f origin gh-pages

