#!/bin/bash

function reload {
  if [[ $(type rvm 2>&- | head -1) = "rvm is a function" ]]; then
    rvm reload
  fi
  source "$HOME/.bash_profile"
}

function update {
  git pull origin master
  git submodule update --init --recursive
  bundle --local
  reload
  reload
}

