#!/bin/bash

function reload {
  pushd ~ > /dev/null
  source "$HOME/.bash_profile"
  popd > /dev/null
}

function update {
  pushd ~ > /dev/null
  git update origin master
  git owner master
  git push -u origin master
  bundle --local
  reload
  reload
  popd ~ > /dev/null
}

alias poop='/System/Library/CoreServices/"Menu Extras"/User.menu/Contents/Resources/CGSession -suspend'

function vcat {
  $shome/bin/vcat "$@"
}

function try_sub {
  local git_dir="$(unset CDPATH; cd -P -- "./$(git rev-parse --show-cdup || true 2>&-)" && pwd -P)"
  ( require sub; PATH="${git_dir}/libexec:$PATH" sub "$@"; )
}

function build {
  try_sub build "$@"
}

function publish {
  try_sub publish "$@"
}

function edit {
  try_sub edit "$@"
}

function bump {
  try_sub bump "$@"
}

function list {
  try_sub list "$@"
}

function new {
  try_sub new "$@"
}

alias ci=vi
