#!/bin/bash

#/ NAME
#/     aoh -- ao-helper subbed script
#/
#/ SYNOPSIS
#/     aoh <ao_command>

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/bin/_treadstone"

require 'sub' "$BASH_SOURCE" "$@"
