#!/bin/bash

#/ NAME
#/     lock - bin/ wrapper to alpha_omega deploy commands
#/
#/ SYNOPSIS
#/     bin/lock

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_treadstone"
require ao

# entry point
function main {
  bundle exec ao "${BASH_SOURCE#*-}" "$@"
}

main "$@"
