#!/bin/bash

#/ NAME
#/     bundle-vim -- bundle release with vim, junas
#/
#/ SYNOPSIS
#/     
#/     bundle-vim


# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"

# load a meat library
source "$shome/libexec/_prime" "$@"

# entry point
function main {
  vim -E -c ':source .vimrc' -c :quit meh
}

require sub "$BASH_SOURCE" "$@"
