#!/bin/bash

#/ NAME
#/     build-perl -- install local::lib, cpan
#/
#/ SYNOPSIS
#/     
#/     build perl

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function main {
  export PERL_MM_USE_DEFAULT=1
  export AUTOMATED_TESTING=1

  cd "$shome/perl5/src/local-lib-1.008004"
  perl Makefile.PL --bootstrap
  make test
  make install
  
  perl -MCPAN -e 'notest install "Module::Build"'

  $shome/bin/build cpan $(cat $shome/Cpanfile)
}

require sub "$BASH_SOURCE" "$@"
