#!/bin/bash

#/ NAME
#/     bundle-node -- bundle release with npm
#/
#/ SYNOPSIS
#/     
#/     bundle-node


# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/bin/_treadstone"

# entry point
function main {
  if [[ ! -f "package.json" ]]; then
    exit 0
  fi

  cd $shome
  rm -rf "$shome/node_modules"
  npm install --production
}

require sub "$BASH_SOURCE" "$@"
