#!/bin/bash

#/ NAME
#/     bundle-assets -- bundle assets, meant to be overridden
#/
#/ SYNOPSIS
#/     
#/     bundle-assets


# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/bin/_treadstone"

# entry point
function main {
  true
}

require sub "$BASH_SOURCE" "$@"
