#!/bin/bash

#/ NAME
#/     pygmentize -- wrapper to call pygmentize under virtualenv
#/
#/ SYNOPSIS
#/     pygmentize ...

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/bin/_treadstone"

# entry point
function main {
  export BUNDLE_GEMFILE="$shome/.doc/Gemfile"
  export shome

  ( cd $shome/.doc && bundle check 2>&1 >/dev/null || { bundle install --quiet --local --path vendor/bundle || bundle check > /dev/null; } )
  exec bundle exec $shome/bin/venv pygmentize "$@"
}

# define command line options:
#   var name, default, description, short option

# parse the command-line
#parse_command_line "$@" || exit $?
#eval set -- "${FLAGS_ARGV}"

# pass arguments to entry point
main "$@"
