#!/bin/bash

#!/bin/bash

#/ NAME
#/     z -- zendesk cli client
#/
#/ SYNOPSIS
#/     z subdomain api yaml_keys

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_treadstone"

# entry point
function main {
  local subdomain="$1"; shift
  local url="$1"; shift

  local dq='"'

  local credentials="$HOME/.zendesk"

  local tmp_curl="$(mktemp -t XXXXXXXX)"
  local tmp_response="$(mktemp -t XXXXXXXX)"
  local tmp_yaml="$(mktemp -t XXXXXXXX)"

  cat > "$tmp_curl" <<EOF
  user = ${dq}$(cat ${credentials})${dq}
EOF
  curl -K - -s --no-keepalive -- "https://${subdomain}.zendesk.com/api/v2/${url}.json" < $tmp_curl > $tmp_response
  rm -f "$tmp_curl"

  cat "$tmp_response" | ruby -e '
    require "json"
    require "yaml"
    Encoding.default_external = Encoding::UTF_8
    puts JSON.load(STDIN.read).to_hash.to_yaml
  ' > "$tmp_yaml"
  rm -f "$tmp_response"

  ryaml "$tmp_yaml" "$@"
  rm -f "$tmp_yaml"
}

# parse the command-line
parse_command_line "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

if [[ "$#" = 0 ]]; then
  set -- patch
fi

# pass arguments to entry point
main "$@"
