source :rubygems

gem "net-ssh", "~> 2.4.0"
gem "json"
gem "microwave"
gem "alpha_omega"

gem "capistrano-campfire"
gem 'airbrake', "~> 3.1.1"
gem "newrelic_rpm", "~> 3.3.4"
gem "flowdock"

gem "tvd-alpha_omega"
