source :rubygems

gem "net-ssh", "~> 2.4.0"
gem "json"
gem "microwave"
gem "alpha_omega"

gem "tvd-bundler"
gem "tvd-git"
gem "tvd-rubygems"
gem "tvd-ssh"
gem "tvd-unicorn"

gem "capistrano-campfire"
gem 'airbrake', "~> 3.1.1"
gem "newrelic_rpm", "~> 3.3.4"
